kind: live
name: Run remote debugging with PyCharm
author: Alexey Naiden
descr: runs remote debugging with PyCharm

inputs:
  local_port:
    descr: local port number for remote debugger
    default: "2211"
  preset:
    descr: resource preset to use, when running the job
    default: ""
  image:
    descr: image name
  volumes_data_remote:
    descr: reference to a data volume
  volumes_code_remote:
    descr: reference to a code volume
  volumes_config_remote:
    descr: reference to a config volume
  volumes_results_remote:
    descr: reference to a results volume
  secret_files:
    default: "[]"
    descr: volumes to be mounted as secrets
  additional_env_vars:
    default: "{}"
    descr: additional environment variables for job

job:
    image: $[[ inputs.image ]]
    preset: $[[ inputs.preset ]]
    volumes: "${{ 
      from_json(inputs.secret_files) + 
      [
        inputs.volumes_data_remote + ':/project/data:rw', 
        inputs.volumes_code_remote + ':/project/modules:rw', 
        inputs.volumes_config_remote + ':/project/config:rw', 
        inputs.volumes_results_remote + ':/project/results:rw'
      ] 
      }}"
    env: "${{ 
      from_json(inputs.additional_env_vars) | 
      {
        'EXPOSE_SSH': 'yes', 
        'PYTHONPATH': '/project/modules'
      } 
      }}"
    port_forward:
      - "$[[ inputs.local_port ]]:22"      
    cmd: bash
